### PR TITLE
workaround for gcc-4.9.3 on windows

### PR DESCRIPTION
**Pull request by jeroenooms**
This is a hopefully temporary workaround for the missing symbol on Windows...

### CODE REVIEW

**Comment by mbjones** [comment]
Thanks, @jeroenooms -- I don't have a windows build system set up to test this at all.  So, I'll just trust you ran all of the tests and all looks good for the merge unless you indicate more testing is needed. It's the 'hopefully' that has me asking... lmk

**Comment by jeroenooms** [comment]
Yes it should be OK. Hopefully we can do a release soon! CRAN would like all packages to be fixed asap for the new Windows toolchain.

**Comment by mbjones** [comment]
Peter and I are in a workshop this week through early next, but then we can hopefully get it tested and pushed out, along with several other packages that need to get pushed to CRAN. Thanks a ton for the windows fixes!

**Comment by jeroenooms** [comment]
CRAN has now fully switched to gcc-4.9.3 so we need to get a patch release out asap: https://cran.r-project.org/web/checks/check_results_redland.html

**Pull request merged**
