### PR TITLE
Homebrew has renamed their repo

### PR DESCRIPTION
**Pull request by jeroenooms**

### CODE REVIEW

**Comment by gothub** [comment]
@jeroenooms Thx for keeping up on the build scripts. Until CRAN gets this fix, their 
Mac OS X builds will fail, yes?

**Comment by jeroenooms** [comment]
Only the building of static binary package on mavericks will fail, but they don't test that a lot. They also have a configuration in which they have homebrew and redland preinstalled on the system, that will just work.

**Comment by gothub** [comment]
OK, thx. I'm not going to proceed with a release to CRAN for just this fix, but will include
this in the next feature release, which might not be for awhile.

**Comment by jeroenooms** [comment]
That's fine by me.

**Pull request merged**
